# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('mturkid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('feedback_clarity', models.TextField(max_length=500)),
                ('feedback_logic', models.TextField(max_length=500)),
                ('feedback_accuracy', models.TextField(max_length=500)),
            ],
        ),
    ]
